apiVersion: v1
data:
  config.py: |
    CORS_ORIGINS = '*'
    PROXY_FIX = {
        'x_for': 1,
        'x_host': 1,
        'x_port': 1,
        'x_proto': 1,
    }
kind: ConfigMap
metadata:
  name: instance-dir
