name: '[build] docker image'

on:
  push:
    branches:
    # - "master"
    - "*"

env:
  DOCKER_REPO: docker-registry.ebrains.eu
  DOCKER_NS: voluba
  DOCKER_IMG: voluba-linear-backend
  DOCKER_TAG: latest

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        docker_tag=${{ env.DOCKER_REPO }}/${{ env.DOCKER_NS }}/${{ env.DOCKER_IMG }}:${{ env.DOCKER_TAG }}
        echo docker_tag=$docker_tag
        docker build -t $docker_tag .
        
        echo DOCKER_BUILT_TAG=$docker_tag >> $GITHUB_ENV
    
    - name: 'Push to docker registry'
      run: |
        echo "Login to docker registry"
        docker login \
          -u '${{ secrets.EBRAINS_DOCKER_REG_USER }}' \
          -p '${{ secrets.EBRAINS_DOCKER_REG_TOKEN }}' \
          docker-registry.ebrains.eu
        echo "Pushing $DOCKER_BUILT_TAG"
        docker push $DOCKER_BUILT_TAG
